version: "3.8"
services:
  warp-clash:
    build: .
    ports:
      - ":3000"
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./account:/app/account
      - ./logs:/app/logs
